# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Stories' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Stories
  pod 'SwiftPriorityQueue', '~> 1.1.2'
  pod 'AnimatedCollectionViewLayout'

  target 'StoriesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StoriesUITests' do
    # Pods for testing
  end

end
